repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.23.1
    hooks:
      - id: nitpick

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.2
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
      - id: yesqa
        additional_dependencies:
          [
            dlint,
            flake8-absolute-import,
            flake8-annotations,
            flake8-bandit,
            flake8-bugbear,
            flake8-builtins,
            flake8-class-attributes-order,
            flake8-commas,
            flake8-comprehensions,
            flake8-debugger,
            flake8-eradicate,
            flake8-executable,
            flake8-fine-pytest,
            flake8-fixme,
            flake8-future-import,
            flake8-implicit-str-concat,
            flake8-mutable,
            flake8-print,
            flake8-pytest-style,
            flake8-simplify,
            flake8-string-format,
            flake8-todo,
            flake8-typing-imports,
            flake8-unused-arguments,
            pep8-naming,
          ]

  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.2.0
    hooks:
      - id: black_nbconvert

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-duplicate-keys,
            --remove-unused-variable,
          ]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          [
            dlint,
            flake8-absolute-import,
            flake8-annotations,
            flake8-bandit,
            flake8-bugbear,
            flake8-builtins,
            flake8-class-attributes-order,
            flake8-commas,
            flake8-comprehensions,
            flake8-debugger,
            flake8-eradicate,
            flake8-executable,
            flake8-fine-pytest,
            flake8-fixme,
            flake8-future-import,
            flake8-implicit-str-concat,
            flake8-mutable,
            flake8-print,
            flake8-pytest-style,
            flake8-simplify,
            flake8-string-format,
            flake8-todo,
            flake8-typing-imports,
            flake8-unused-arguments,
            pep8-naming,
          ]
