name: skritter

channels:
  - conda-forge

dependencies:
  - python = 3.9
  - click = 7.1
  - more-itertools = 8.6
  - pynput = 1.7
  - tqdm = 4.55
  - pip
  - pip:
      - --requirement=.pre-commit-hooks/python/requirements.txt
